version: '3.7'
services:
  mysql:
    image: mysql
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./volumes/mysql_dev:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_dev
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
    ports:
      - "3308:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080